version: 2.1
orbs:
  node: circleci/node@5.1.1
jobs:
  test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          node-version: '21.2'
      - node/install-packages
      - run:
          command: npm run test
workflows:
  test:
    jobs:
      - test
